name: actions
on: [push]
jobs:
  build-blue-hal:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authentication
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: |
            ${{ secrets.PATHFINDERDELL_PRIVATE_KEY }}

      - name: Cargo initialisation
        run: |
          ~/.cargo/bin/rustup default nightly
          ~/.cargo/bin/rustup update

      - name: Documentation
        run: ~/.cargo/bin/cargo doc

      - name: Tests
        run: ~/.cargo/bin/cargo test
